name: update
on:
  schedule:
    # Run weekly
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: output-update
  TITLE: "chore(output): weekly `gen_output.sh`"
  BODY: |
    This is an automated update to the output and references.

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Update
        run: |
          git config --global user.email "update@update.com"
          git config --global user.name "update"
          ./scripts/gen_output.sh

      - name: Create commit
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY">> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ steps.msg.outputs.commit_message }}
          title: ${{ env.TITLE }}
          body: ${{ steps.msg.outputs.body }}
          branch: ${{ env.BRANCH }}
